name: Hola Mundo Workflow

on:
  push:
    branches:
      - master  # O usa 'master' si esa es la rama principal en tu repo

jobs:
  run:
    runs-on: self-hosted  # Usamos una máquina virtual Ubuntu
    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Esto asegura que el código del repositorio esté disponible en el runner

    - name: Imprimir Hola Mundo
      run: echo "Hola Mundo"  # Este comando imprimirá "Hola Mundo" en la consola
